---
# Python CircleCI 2.0 configuration file
#
# INFO: Check CircleCI documentation for more details
#       https://circleci.com/docs/2.0/language-python/

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  lint:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6

    steps:
      - checkout

      - restore_cache:
          # Increasingly general patterns to restore
          # https://circleci.com/docs/2.0/caching/#using-keys-and-templates
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - pip-cache-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Install Python packages
          command: make sync

      - save_cache:
          # Pipenv venv and pip cached wheels
          paths:
            - "~/.local"
            - "~/.cache"
          key: pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run linters
          command: make lint


  unit:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - pip-cache-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Install Python packages
          command: make sync

      - save_cache:
          paths:
            - "~/.local"
            - "~/.cache"
          key: pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run unit tests
          command: make unit

      - codecov/upload:
          file: ./coverage.xml

  functional-s3:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6
        environment:
          TENTACLIO__CONN__S3_TEST: s3://public_key:private_key@tentaclio-bucket

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Python packages
          command: make sync

      - run:
          name: Run S3 functional tests
          command: make functional-s3
      
      - codecov/upload:
          file: ./coverage.xml

  functional-ftp:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6
        environment:
          TENTACLIO__CONN__FTP_TEST: ftp://octopus:tentacle@localhost

      - image: mauler/simple-ftp-server
        environment:
          FTP_USER: octopus
          FTP_PASS: tentacle

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Python packages
          command: make sync

      - run:
          name: Run postgres functional tests
          command: make functional-ftp
      
      - codecov/upload:
          file: ./coverage.xml

  functional-sftp:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6
        environment:
          TENTACLIO__CONN__SFTP_TEST: sftp://octopus:tentacle@localhost:22

      - image: atmoz/sftp
        command: octopus:tentacle:::upload

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Python packages
          command: make sync

      - run:
          name: Run sftp functional tests
          command: make functional-sftp
      
      - codecov/upload:
          file: ./coverage.xml

  functional-postgres:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6
        environment:
          TENTACLIO__CONN__POSTGRES_TEST: postgresql://:@localhost:5432/tentaclio-db

      - image: circleci/postgres:9.5.10
        environment:
          # CircleCI img run under `circleci` user
          POSTGRES_USER: circleci
          POSTGRES_DB: tentaclio-db

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Python packages
          command: make sync

      - run:
          name: Run postgres functional tests
          command: make functional-postgres
      
      - codecov/upload:
          file: ./coverage.xml

  deploy:
    working_directory: ~/lib

    docker:
      - image: circleci/python:3.6.6

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Build wheel
          command: make package

      - store_artifacts:
          path: dist
          destination: wheel

workflows:
  version: 2

  test-build-deploy:
    jobs:
      - lint
      - unit
      - functional-s3:
          requires:
            - lint
            - unit
      - functional-ftp:
          requires:
            - lint
            - unit
      - functional-sftp:
          requires:
            - lint
            - unit
      - functional-postgres:
          requires:
            - lint
            - unit
      - deploy:
          requires:
            - functional-s3
            - functional-ftp
            - functional-sftp
            - functional-postgres
          filters:
            branches:
              # Change this to the branch you want to deploy into test
              only: master
